

POST http://localhost:8080/login
Content-Type: application/json

{
    "username": "user1",
    "password": "pass"
}

###

GET http://localhost:8080/users?name=someName1
Authorization: nl3oisu6zgl

###
